<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Importers.Xpln.Tests</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Importers.Xpln.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="XplnRepositoryWithExcelTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.9.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
    <PackageReference Include="System.Data.Odbc" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Importers.Access\Importers.Access.csproj" />
    <ProjectReference Include="..\Importers.Interfaces\Importers.Interfaces.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\Importers.Services\Importers.Services.csproj" />
    <ProjectReference Include="..\Importers.Xpln\Importers.Xpln.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Test data\**\*.ods" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.8.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="2.2.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="4.2.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="4.2.3" />
  </ItemGroup>
</Project>
