<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Importers.Xpln.Tests</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Importers.Xpln.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="XplnRepositoryWithExcelTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.1" />
    <PackageReference Include="System.Data.Odbc" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Importers.Access\Access.csproj" />
    <ProjectReference Include="..\Importers.Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\Importers.Services\Services.csproj" />
    <ProjectReference Include="..\Importers.Xpln\Xpln.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Test data\**\*.ods" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
