<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Importers.Interfaces.Tests</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Importers.Interfaces.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\Importers.Interfaces\Importers.Interfaces.csproj" />
    <ProjectReference Include="..\Importers.Services\Importers.Services.csproj" />
    <ProjectReference Include="..\Importers.Xpln\Importers.Xpln.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Test data\**\*.ods" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
