<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Importers.Interfaces.Tests</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Importers.Interfaces.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\Importers.Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\Importers.Services\Services.csproj" />
    <ProjectReference Include="..\Importers.Xpln\Xpln.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Test data\**\*.ods" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.8.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="2.2.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="4.2.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="4.2.3" />
  </ItemGroup>
</Project>
