<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<AssemblyName>Tellurian.Trains.Schedules.Importers.Services.Tests</AssemblyName>
		<RootNamespace>Tellurian.Trains.Schedules.Importers.Services.Tests</RootNamespace>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Services\Services.csproj" />
	</ItemGroup>

</Project>
