<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Model.Databases</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Model.Databases</RootNamespace>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageReleaseNotes>
    </PackageReleaseNotes>
    <Title>$(AssemblyName)</Title>
    <Description>Entity Framework Core support for Tellurian.Trains.Schedules.Model.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.301">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Importers.Interfaces\Importers.Interfaces.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup></Project>
