<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Planning.Tests</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Planning.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Planning\Planning.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>
</Project>
