namespace Tellurian.Trains.Schedules.Model.Notes;

/// <summary>
/// Derives, for one station call, the notes generated by the cargo flows of the call's own train.
/// </summary>
/// <remarks>
/// <para>
/// Unlike the vehicle notes, these need no plan passed in: a cargo flow belongs directly to its train
/// (<c>Train.CargoFlows</c>), and a call always knows its train, so everything needed is already in hand.
/// </para>
/// <para>
/// On a shunting task this is the shunting instruction — what to do with the wagons the task handles —
/// and nothing else. The task has no route and so no cargo block to lean on, the instruction is the whole
/// of what it is for, and its two ends are the same call, so a couple and an uncouple note there would
/// only crowd it.
/// </para>
/// <para>
/// On a travelling train it is instead the two notes the flow gives the station's dispatcher: where the
/// wagons coupled on here are bound, and which destinations the wagons taken off here are for. The loco
/// driver reads neither — their booklet states the flow in its cargo block — which is why both are
/// marked as station notes only (see <c>CargoFlowTrainPartExtensions.DepartureNotes</c>).
/// </para>
/// </remarks>
public static class CargoFlowCallNoteExtensions
{
    extension(StationCall call)
    {
        /// <summary>
        /// The notes the train's cargo flows generate at this call: those of every flow that begins or
        /// ends here. On a shunting task the two are the same call, and the flow is counted once.
        /// </summary>
        public IEnumerable<ICallNote> CargoFlowNotes
        {
            get
            {
                call = call.ValueOrException(nameof(call));
                if (call.Train is not { } train) return [];

                // By reference, not by value: a train can hold two calls that compare equal, and a
                // flow is bounded by the very call instances the train owns.
                var begins = train.CargoFlows.Where(flow => ReferenceEquals(flow.From, call)).ToList();
                var ends = train.CargoFlows.Where(flow => ReferenceEquals(flow.To, call)).ToList();

                if (train.IsShuntingTask) return [.. begins.Union(ends).SelectMany(flow => flow.ShuntingNotes)];

                // One note per kind, naming the destinations of all its flows: several flows beginning at
                // the same call would otherwise repeat the same sentence once per flow.
                var departures = begins.SelectMany(flow => flow.DepartureNotes).OfType<CargoFlowDestinationNote>().ToList();
                var arrivals = ends.SelectMany(flow => flow.ArrivalNotes).OfType<CargoFlowUncoupleNote>().ToList();
                List<ICallNote> result = [];
                if (departures.Count > 0)
                    result.Add(departures[0] with { Parts = [.. departures.SelectMany(note => note.Parts)] });
                if (arrivals.Count > 0)
                {
                    var parts = arrivals.SelectMany(note => note.Parts).ToList();
                    result.Add(arrivals[0] with { Parts = parts, Handling = call.ArrivedWagonHandlingFor(parts) });
                }
                return result;
            }
        }

        /// <summary>
        /// What is done with the wagons that arrive here: a shadow station moves them on or places them at
        /// the table, any other shunting yard shunts them on or to the customer, and anywhere else they are
        /// shunted to the customers only where a flow asks for that.
        /// </summary>
        private ArrivedWagonHandling ArrivedWagonHandlingFor(IReadOnlyList<CargoFlowTrainPart> flows)
        {
            if (call.OperationLocation is Station { IsShadow: true }) return ArrivedWagonHandling.MoveToDepartingTrackOrTable;
            if (call.OperationLocation is Station station && call.OperationLocation.Layout is { } layout &&
                (station.Regions.Count > 0 || layout.LocationsCargoServedFrom(station).Count > 0))
                return ArrivedWagonHandling.ShuntToDepartingTrackOrCustomer;
            return flows.Any(flow => flow.AlsoShuntAfterArrival)
                ? ArrivedWagonHandling.ShuntToCustomers
                : ArrivedWagonHandling.None;
        }
    }
}
