namespace Tellurian.Trains.Schedules.Model.Notes;

/// <summary>
/// Derives, for one station call, the notes generated by the cargo flows of the call's own train.
/// </summary>
/// <remarks>
/// <para>
/// Unlike the vehicle notes, these need no plan passed in: a cargo flow belongs directly to its train
/// (<c>Train.CargoFlows</c>), and a call always knows its train, so everything needed is already in hand.
/// </para>
/// <para>
/// Today this is the shunting instruction of a shunting task — what to do with the wagons the task
/// handles. A cargo flow on a travelling train states where its wagons go in the cargo block of the duty
/// page instead, and contributes nothing here; a shunting task has no such block to lean on, because it
/// has no route, and the instruction is the whole of what it is for.
/// </para>
/// </remarks>
public static class CargoFlowCallNoteExtensions
{
    extension(StationCall call)
    {
        /// <summary>
        /// The notes the train's cargo flows generate at this call: those of every flow that begins or
        /// ends here. On a shunting task the two are the same call, and the flow is counted once.
        /// </summary>
        public IEnumerable<ICallNote> CargoFlowNotes
        {
            get
            {
                call = call.ValueOrException(nameof(call));
                if (call.Train is not { } train) return [];
                return
                [
                    // By reference, not by value: a train can hold two calls that compare equal, and a
                    // flow is bounded by the very call instances the train owns.
                    .. train.CargoFlows
                        .Where(flow => ReferenceEquals(flow.From, call) || ReferenceEquals(flow.To, call))
                        .SelectMany(flow => flow.ShuntingNotes)
                ];
            }
        }
    }
}
