<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<AssemblyName>Tellurian.Trains.Schedules.Importers.Services.Tests</AssemblyName>
		<RootNamespace>Tellurian.Trains.Schedules.Importers.Services.Tests</RootNamespace>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Importers.Interfaces\Interfaces.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Importers.Services\Services.csproj" />
		<ProjectReference Include="..\Importers.Xpln\Xpln.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Test data\**\*.ods" CopyToOutputDirectory="Always" />
	</ItemGroup>

</Project>
