<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Importers.Interfaces</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Importers.Interfaces</RootNamespace>
    <PackageId>$(AssemblyName)</PackageId>
    <Title>$(AssemblyName)</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.301">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Tellurian.Utilities" Version="1.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup></Project>