<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>Tellurian.Trains.Schedules.Planning.Components.Tests</AssemblyName>
    <RootNamespace>Tellurian.Trains.Schedules.Planning.Components.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Planning.Components\Planning.Components.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="4.3.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>
</Project>
