//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Schedules.Model.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Schedules.Model.Resources.Notes", typeof(Notes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to all destinations.
        /// </summary>
        internal static string AllDestinations {
            get {
                return ResourceManager.GetString("AllDestinations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to and beyond.
        /// </summary>
        internal static string AndBeyond {
            get {
                return ResourceManager.GetString("AndBeyond", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to and local destinations.
        /// </summary>
        internal static string AndLocalDestinations {
            get {
                return ResourceManager.GetString("AndLocalDestinations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to and local destinations and beyond.
        /// </summary>
        internal static string AndLocalDestinationsAndBeyond {
            get {
                return ResourceManager.GetString("AndLocalDestinationsAndBeyond", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Axles × {0}.
        /// </summary>
        internal static string Axles {
            get {
                return ResourceManager.GetString("Axles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brings wagons to {0}.
        /// </summary>
        internal static string BringsWagonsTo {
            get {
                return ResourceManager.GetString("BringsWagonsTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Couple {0} to train..
        /// </summary>
        internal static string CoupleToTrain {
            get {
                return ResourceManager.GetString("CoupleToTrain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Couple {0} to train in position {1}..
        /// </summary>
        internal static string CoupleToTrainInPosition {
            get {
                return ResourceManager.GetString("CoupleToTrainInPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move traction unit {0} from parking to departure track..
        /// </summary>
        internal static string MoveTractionUnitFromParkingToDepartureTrack {
            get {
                return ResourceManager.GetString("MoveTractionUnitFromParkingToDepartureTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move traction unit {0} to parking..
        /// </summary>
        internal static string MoveTractionUnitToParking {
            get {
                return ResourceManager.GetString("MoveTractionUnitToParking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reinforces {0} between {1} and {2}..
        /// </summary>
        internal static string ReinforcesBetweenAnd {
            get {
                return ResourceManager.GetString("ReinforcesBetweenAnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uncouple {0} from train..
        /// </summary>
        internal static string UncoupleFromTrain {
            get {
                return ResourceManager.GetString("UncoupleFromTrain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use {0}..
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wagons × {0}.
        /// </summary>
        internal static string Wagons {
            get {
                return ResourceManager.GetString("Wagons", resourceCulture);
            }
        }
    }
}
