//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Schedules.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Schedules.Model.Resources.Notes", typeof(Notes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all destinations.
        /// </summary>
        internal static string AllDestinations {
            get {
                return ResourceManager.GetString("AllDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and beyond.
        /// </summary>
        internal static string AndBeyond {
            get {
                return ResourceManager.GetString("AndBeyond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axles × {0}.
        /// </summary>
        internal static string Axles {
            get {
                return ResourceManager.GetString("Axles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings wagons to {0}.
        /// </summary>
        internal static string BringsWagonsTo {
            get {
                return ResourceManager.GetString("BringsWagonsTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uncouple wagons for {0}..
        /// </summary>
        internal static string UncoupleWagonsFor {
            get {
                return ResourceManager.GetString("UncoupleWagonsFor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shunt arriving wagons from {0} to cargo customers..
        /// </summary>
        internal static string ShuntArrivingWagonsFromToCargoCustomers {
            get {
                return ResourceManager.GetString("ShuntArrivingWagonsFromToCargoCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shunt arriving wagons to cargo customers..
        /// </summary>
        internal static string ShuntArrivingWagonsToCargoCustomers {
            get {
                return ResourceManager.GetString("ShuntArrivingWagonsToCargoCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fetch wagons to {0} from cargo customers..
        /// </summary>
        internal static string FetchWagonsToFromCargoCustomers {
            get {
                return ResourceManager.GetString("FetchWagonsToFromCargoCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Circulate locomotive..
        /// </summary>
        internal static string CirculateTractionUnit {
            get {
                return ResourceManager.GetString("CirculateTractionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple {0} to train..
        /// </summary>
        internal static string CoupleToTrain {
            get {
                return ResourceManager.GetString("CoupleToTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple {0} to train in position {1}..
        /// </summary>
        internal static string CoupleToTrainInPosition {
            get {
                return ResourceManager.GetString("CoupleToTrainInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosses {0}.
        /// </summary>
        internal static string Crosses {
            get {
                return ResourceManager.GetString("Crosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange transferring passengers here..
        /// </summary>
        internal static string ExchangeTransferringPassengers {
            get {
                return ResourceManager.GetString("ExchangeTransferringPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in sessions {0}.
        /// </summary>
        internal static string InSessions {
            get {
                return ResourceManager.GetString("InSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is overtaken by {0}.
        /// </summary>
        internal static string IsOvertakenBy {
            get {
                return ResourceManager.GetString("IsOvertakenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave key {0} from {1}..
        /// </summary>
        internal static string LeaveKeyFrom {
            get {
                return ResourceManager.GetString("LeaveKeyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave key from {0}..
        /// </summary>
        internal static string LeaveUnnamedKeyFrom {
            get {
                return ResourceManager.GetString("LeaveUnnamedKeyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before departure, drive {0} from parking space to departure track..
        /// </summary>
        internal static string MoveTractionUnitFromParkingToDepartureTrack {
            get {
                return ResourceManager.GetString("MoveTractionUnitFromParkingToDepartureTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After arrival, drive {0} from arrival track to parking space..
        /// </summary>
        internal static string MoveTractionUnitToParking {
            get {
                return ResourceManager.GetString("MoveTractionUnitToParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch {0} from track {1}..
        /// </summary>
        internal static string FetchFromTrack {
            get {
                return ResourceManager.GetString("FetchFromTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string OnSessions {
            get {
                return ResourceManager.GetString("OnSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Put {0} on track {1}..
        /// </summary>
        internal static string PutOnTrack {
            get {
                return ResourceManager.GetString("PutOnTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shunt wagons to departure track before departure..
        /// </summary>
        internal static string ShuntWagonsToDepartureTrack {
            get {
                return ResourceManager.GetString("ShuntWagonsToDepartureTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shunt wagons to their arrival track after arrival..
        /// </summary>
        internal static string ShuntWagonsToArrivalTrack {
            get {
                return ResourceManager.GetString("ShuntWagonsToArrivalTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No exchange.
        /// </summary>
        internal static string NoExchange {
            get {
                return ResourceManager.GetString("NoExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stop.
        /// </summary>
        internal static string NoStop {
            get {
                return ResourceManager.GetString("NoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shunting task {0}-{1}.
        /// </summary>
        internal static string ShuntingTaskFromTo {
            get {
                return ResourceManager.GetString("ShuntingTaskFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtakes {0}.
        /// </summary>
        internal static string Overtakes {
            get {
                return ResourceManager.GetString("Overtakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up key {0} for unlocking {1}..
        /// </summary>
        internal static string PickUpKeyForUnlocking {
            get {
                return ResourceManager.GetString("PickUpKeyForUnlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up key for unlocking {0}..
        /// </summary>
        internal static string PickUpUnnamedKeyForUnlocking {
            get {
                return ResourceManager.GetString("PickUpUnnamedKeyForUnlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforces {0} between {1} and {2}..
        /// </summary>
        internal static string ReinforcesBetweenAnd {
            get {
                return ResourceManager.GetString("ReinforcesBetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of traction unit from {0} to {1}..
        /// </summary>
        internal static string TractionUnitExchange {
            get {
                return ResourceManager.GetString("TractionUnitExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string TrainMeetAtTime {
            get {
                return ResourceManager.GetString("TrainMeetAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn and circulate locomotive..
        /// </summary>
        internal static string TurnAndCirculateTractionUnit {
            get {
                return ResourceManager.GetString("TurnAndCirculateTractionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn locomotive..
        /// </summary>
        internal static string TurnTractionUnit {
            get {
                return ResourceManager.GetString("TurnTractionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncouple {0} from train..
        /// </summary>
        internal static string UncoupleFromTrain {
            get {
                return ResourceManager.GetString("UncoupleFromTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0}..
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagons × {0}.
        /// </summary>
        internal static string Wagons {
            get {
                return ResourceManager.GetString("Wagons", resourceCulture);
            }
        }
    }
}
